# This workflow triggers on pushes to the main branch.
# It sets up the Flutter environment and builds the web application.


name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Curated repository
        uses: actions/checkout@v4
      - name: Set up Flutter environment
        uses: subosito/flutter-action@v2.21.0
        with:
          channel: stable
          flutter-version: 3.32.0
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build web
