#  == Namecheap Flutter Web Deployment Workflow ==
# This GitHub Actions workflow builds a Flutter web application and deploys it to a Namecheap hosting account via FTP.

name: Deploy Flutter Web to Namecheap

# This action runs on every push to the 'main' branch
on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2. Setup the Flutter SDK in the runner
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.21.0
        with:
          channel: 'stable'
          flutter-version: 3.32.0

      # 3. Get Flutter dependencies
      - name: Get Dependencies
        run: flutter pub get

      # 4. Build the Flutter web application
      - name: Build Flutter Web
        run: flutter build web --release

      # 5. Deploy the build files to Namecheap via FTP
      - name: Deploy to Namecheap
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.curated.forum
          username: quabiee-deployer@curated.forum
          password: curatedFxrxm001#
          protocol: ftps
          port: 21
          # local-dir: ./build/web/ # The directory of files to upload
          # server-dir: ./public_html/ # The destination directory on the server